version: "3"

services:
  chatgpt-for-telegram:
    container_name: chatgpt-for-telegram
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - MONGODB_HOST=database.mongodb.net
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - TELEGRAM_TOKEN=yourbottoken
      - USER_WHITELIST = 89727e9, mamador,   rrjrj,6077244180
      - SUDO_USERS=69959, ejemplo1,ejemplo2
      - new_dialog_timeout=7200
      - return_n_generated_images=4
#opcionalmente    volumes:
#      - /ruta-fuera-del-docker/mi-configuracion:/config
