telegram_token: "5604707914:AAG2tZ5i-r81A0rPooXb1PeMcmyvtZppeeE"
openai_api_key: "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"
use_chatgpt_api: true
allowed_telegram_usernames: []  # if empty, the bot is available to anyone
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)

chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006
