available_text_models: ["gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-4-1106-preview", "gpt-4", "text-davinci-003"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT is that well-known model. It's <b>fast</b> and <b>cheap</b>. Ideal for everyday tasks. If there are some tasks it can't handle, try the <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT-16K
    description: ChatGPT is that well-known model. It's <b>fast</b> and <b>cheap</b>. Ideal for everyday tasks. If there are some tasks it can't handle, try the <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4 is the <b>smartest</b> and most advanced model in the world. But it is slower and not as cost-efficient as ChatGPT. Best choice for <b>complex</b> intellectual tasks.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  gpt-4-1106-preview:
    type: chat_completion
    name: GPT-4 Turbo
    description: GPT-4 Turbo is a <b>faster</b> and <b>cheaper</b> version of GPT-4. It's as smart as GPT-4, so you should use it instead of GPT-4.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: GPT-3.5 is a legacy model. Actually there is <b>no reason to use it</b>, because it is more expensive and slower than ChatGPT, but just about as smart.

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006